---

- name: Configure iSCSI Gateways
  hosts: '{{ "iscsi-gws" if install_type == "rpm" else "osds" }}'
  become: true

  tasks:

    - name: Add ISCSI Gateway {{ inventory_hostname }}
      shell: ceph dashboard iscsi-gateway-add http://admin:admin@{{ inventory_hostname }}:5000
      when: install_type == "rpm"

    - name: Add ISCSI Gateway {{ inventory_hostname }}
      shell: podman exec ceph-mon-{{ inventory_hostname }} ceph dashboard iscsi-gateway-add http://admin:admin@{{ inventory_hostname }}:5000
      when: install_type == "csd"
