---

- name: Prepare host subscription and packages
  include: prepare-environment/prepare-environment-rpm-subscription.yml

- name: Prepare environment hosts
  include: prepare-environment/prepare-environment-hosts.yml

- name: Generate SSH key for vagrant hosts
  include: prepare-environment/prepare-environment-vagrant-generate-ssh.yml

- name: Add SSH key for vagrant hosts
  include: prepare-environment/prepare-environment-vagrant-add-ssh.yml

- name: Allow SSH tcp/22
  include: prepare-environment/prepare-environment-allow-ssh.yml
